In [2]:
import pandas as pd
import glob
import os

# setting the path for joining multiple files
files = os.path.join("C:\\Users\\pbehera\\OneDrive - GXO\Desktop\\Python\\EWC", "*.csv")

# list of merged files returned
files = glob.glob(files)


# joining files with concat and read_csv
df = pd.concat(map(pd.read_csv, files), ignore_index=True)

In [3]:
df

,AS_OF_DATE,SITE_ID,CLIENT_ID,ITEM,LOC,QTY_ON_HAND,PALLETS_ON_HAND
0,12-APR-22,FPA,1002,21221,B072E,432,1
1,12-APR-22,FPA,1002,21221,B075D,432,1
2,12-APR-22,FPA,1002,21221,B090E,432,1
3,12-APR-22,FPA,1002,21221,B092E,432,1
4,12-APR-22,FPA,1002,21221,C010D,432,1
...,...,...,...,...,...,...,...
96922,23-APR-22,RNE,1002,EWCXLWSSBX,COOLWALL05,21000,1
96923,23-APR-22,RNE,1002,EWCXLWSSBX,COOLWALL06,21000,1
96924,23-APR-22,RNE,1002,EWCXLWSSBX,COOLWALL07,21000,1
96925,23-APR-22,RNE,1002,EWCXLWSSBX,COOLWALL08,21000,1
96926,23-APR-22,RNE,1002,EWCXLWSSBX,COOLWALL09,21000,1